---
- name: VMware Disk Info
  hosts: local
  tasks:
  - name: Gather disk info from virtual machine using name
    community.vmware.vmware_guest_disk_info:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ vcenter_dc }}"
      name: "{{ vm_name }}"
      validate_certs: false
    delegate_to: localhost
    register: disk_info

  - name: Print return information from the previous task
    ansible.builtin.debug:
      var: disk_info